"""Regression tests for the Legal Structure Extractor golden fixtures (VNLRAG-34).

Golden fixture set under tests/fixtures/golden/ (one subdir per document type:
luat/ nd/ tt/). Each golden document ships (a) the source .txt, (b) a
manifest.json valid against templates/corpus-manifest.schema.json, and (c)
expected_provisions.json — the EXACT extractor output (hierarchy, provision_id,
point labels, short_point, determinism-bearing fields) generated by running the
extractor at creation time, plus the retained: true gold annotation.

These tests validate:
- the extractor output matches expected_provisions.json EXACTLY (full record
  equality, so provision_id set, node_kind, point labels and hierarchy are
  regression-locked) and is stable across runs (determinism);
- every provision_id matches the legal-provision schema pattern and every
  expected record validates against the schema;
- d)/đ) separation: diem-d and diem-đ are distinct provision_ids, with the
  full a-b-c-d-đ-e point run for nd Điều 5 Khoản 1 and luat Điều 3 Khoản 1
  (rules §4, stable_id_diem_d_dd.json semantics);
- short Points are retained with no token-length threshold (rules §5),
  including the luat Điều 8 Khoản 1 d/đ cases;
- manifests are schema-valid and consistent with the golden documents.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import UTC, datetime
from pathlib import Path

import pytest
from jsonschema import Draft7Validator

from app.ingestion.document_ir import BoundingBox, DocumentElement, ParsedDocument, ParsedPage
from app.ingestion.structure_extractor import ExtractedLegalProvision, LegalStructureExtractor
from scripts.validate_manifest import validate_manifest

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures" / "golden"
TEMPLATES_DIR = Path(__file__).resolve().parents[2] / "templates"

PROVISION_SCHEMA = json.loads(
    (TEMPLATES_DIR / "legal-provision.schema.json").read_text(encoding="utf-8")
)
PROVISION_ID_PATTERN = PROVISION_SCHEMA["properties"]["provision_id"]["pattern"]
PROVISION_ID_RE = re.compile(PROVISION_ID_PATTERN)

DOC_TYPES = ["luat", "nd", "tt"]

# Full a-b-c-d-đ-e point runs the golden set must contain (rules §4).
FULL_POINT_RUNS = {
    "nd-168-2024__dieu-5__khoan-1": ["a)", "b)", "c)", "d)", "đ)", "e)"],
    "luat-36-2024__dieu-3__khoan-1": ["a)", "b)", "c)", "d)", "đ)", "e)"],
}

# Ticket-named luat Điều 8 Khoản 1 points (rules §5 example 3): all must be
# retained in the output; d/đ are additionally flagged short_point=True.
SHORT_POINT_IDS = {
    "luat-36-2024__dieu-8__khoan-1__diem-a",
    "luat-36-2024__dieu-8__khoan-1__diem-d",
    "luat-36-2024__dieu-8__khoan-1__diem-đ",
}


def _golden_dir(doc_type: str) -> Path:
    return FIXTURES_DIR / doc_type


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _expected(doc_type: str) -> dict:
    return _read_json(_golden_dir(doc_type) / "expected_provisions.json")


def _build_document(text: str, document_id: str) -> ParsedDocument:
    """Deterministic IR built from the golden .txt.

    One paragraph element per non-empty line, with stable element_id /
    reading_order / bbox derived from the original line index. This mirrors the
    fixture generator (tests/fixtures/golden/ generation script) so the
    regression reproduces the exact extractor input the golden output was
    created from (same convention as tests/test_structure_extractor.py).
    """

    elements: list[DocumentElement] = []
    for index, line in enumerate(text.splitlines()):
        if not line.strip():
            continue
        elements.append(
            DocumentElement(
                element_id=f"e{index}",
                element_type="paragraph",
                text=line,
                page_number=1,
                bbox=BoundingBox(
                    left=0.1, top=index / 100, right=0.9, bottom=(index + 1) / 100
                ),
                reading_order=index,
                parent_element_id=None,
                source_parser="TEST",
                parser_version="test-1",
                parser_confidence=None,
                raw_reference={"index": index},
            )
        )
    return ParsedDocument(
        parsed_document_id="parsed-1",
        document_id=document_id,
        parser="TEST",
        parser_version="test-1",
        ir_schema_version="document-ir-v2",
        source_object_key="fixture",
        pages=[ParsedPage(page_number=1, width=1, height=1, text=None, elements=elements)],
        parse_started_at=datetime(2024, 1, 1, tzinfo=UTC),
        parse_completed_at=datetime(2024, 1, 1, 0, 0, 1, tzinfo=UTC),
        quality_report={},
    )


def _extract(doc_type: str) -> list[dict]:
    expected = _expected(doc_type)
    fixture_path = _golden_dir(doc_type) / expected["fixture"]
    document = _build_document(
        fixture_path.read_text(encoding="utf-8"), expected["document_id"]
    )
    provisions = LegalStructureExtractor().extract(
        document,
        document_version_id=expected["document_version_id"],
        document_slug=expected["document_slug"],
    )
    return [provision.model_dump() for provision in provisions]


def _expected_core_records(doc_type: str) -> list[dict]:
    """Expected extractor records without the retained gold annotation."""

    return [
        {key: value for key, value in record.items() if key != "retained"}
        for record in _expected(doc_type)["provisions"]
    ]


@pytest.mark.parametrize("doc_type", DOC_TYPES)
def test_golden_fixture_files_exist(doc_type: str) -> None:
    expected = _expected(doc_type)
    assert expected["document_id"]
    assert expected["document_slug"]
    assert expected["document_version_id"]
    assert expected["fixture"]
    assert isinstance(expected["provisions"], list) and expected["provisions"]
    assert (_golden_dir(doc_type) / expected["fixture"]).exists(), (
        f"{doc_type}: fixture {expected['fixture']} missing"
    )
    assert (_golden_dir(doc_type) / "manifest.json").exists(), f"{doc_type}: manifest missing"


def test_manifests_are_schema_valid_and_consistent() -> None:
    """Every manifest passes corpus-manifest.schema.json + cross-field rules and
    matches its golden document (document_id / document_type / file_hash)."""

    for doc_type in DOC_TYPES:
        manifest = _read_json(_golden_dir(doc_type) / "manifest.json")
        assert validate_manifest(manifest) == [], f"{doc_type}: manifest invalid"
        expected = _expected(doc_type)
        assert manifest["document_id"] == expected["document_id"], doc_type
        assert manifest["document_type"] == expected["document_type"], doc_type
        fixture_path = _golden_dir(doc_type) / expected["fixture"]
        digest = hashlib.sha256(fixture_path.read_bytes()).hexdigest()
        assert manifest["file_hash"] == digest, f"{doc_type}: file_hash != fixture sha256"


@pytest.mark.parametrize("doc_type", DOC_TYPES)
def test_extractor_output_matches_expected_exactly(doc_type: str) -> None:
    """The extractor run over the golden .txt reproduces expected_provisions.json
    EXACTLY (provision_id set, node_kind, point labels, hierarchy, and every
    deterministic field of the record)."""

    extracted = _extract(doc_type)
    assert extracted == _expected_core_records(doc_type), (
        f"{doc_type}: extractor output deviates from expected_provisions.json"
    )


@pytest.mark.parametrize("doc_type", DOC_TYPES)
def test_extractor_output_is_deterministic(doc_type: str) -> None:
    """Two runs over the same input produce byte-identical records."""

    first = _extract(doc_type)
    second = _extract(doc_type)
    assert first == second
    assert first == _expected_core_records(doc_type)


@pytest.mark.parametrize("doc_type", DOC_TYPES)
def test_all_expected_records_are_retained(doc_type: str) -> None:
    """Every provision in the golden output is a retained provision."""

    for record in _expected(doc_type)["provisions"]:
        assert record["retained"] is True, f"{doc_type}: {record['provision_id']}"


@pytest.mark.parametrize("doc_type", DOC_TYPES)
def test_all_provision_ids_match_schema_pattern(doc_type: str) -> None:
    for record in _expected_core_records(doc_type):
        provision_id = record["provision_id"]
        assert PROVISION_ID_RE.fullmatch(provision_id), (
            f"{doc_type}: provision_id {provision_id!r} does not match schema pattern"
        )


@pytest.mark.parametrize("doc_type", DOC_TYPES)
def test_expected_records_are_schema_valid(doc_type: str) -> None:
    """Every expected record validates against templates/legal-provision.schema.json."""

    validator = Draft7Validator(PROVISION_SCHEMA)
    for record in _expected_core_records(doc_type):
        provision = ExtractedLegalProvision.model_validate(record)
        errors = list(validator.iter_errors(provision.to_schema_dict()))
        assert not errors, f"{doc_type}: {record['provision_id']}: {errors}"


@pytest.mark.parametrize("doc_type", DOC_TYPES)
def test_d_and_dd_point_labels_are_distinct(doc_type: str) -> None:
    """d)/đ) separation: both labels exist, map to stable IDs diem-d / diem-đ,
    and never collide — even within the same clause (rules §4, stable-ID
    semantics)."""

    records = _expected_core_records(doc_type)
    d_records = [record for record in records if record.get("point_label") == "d)"]
    dd_records = [record for record in records if record.get("point_label") == "đ)"]
    assert d_records, f"{doc_type}: thiếu nhãn d)"
    assert dd_records, f"{doc_type}: thiếu nhãn đ)"

    d_ids = {record["provision_id"] for record in d_records}
    dd_ids = {record["provision_id"] for record in dd_records}
    assert all(provision_id.endswith("__diem-d") for provision_id in d_ids)
    assert all(provision_id.endswith("__diem-đ") for provision_id in dd_ids)
    assert not d_ids & dd_ids, f"{doc_type}: diem-d và diem-đ va chạm"

    # Within any clause that contains both labels, d) and đ) stay two distinct
    # provision_ids (diem-d vs diem-đ must not collapse).
    for article, clause in {
        (record["article"], record["clause"]) for record in d_records + dd_records
    }:
        clause_d = {
            record["provision_id"]
            for record in d_records
            if record["article"] == article and record["clause"] == clause
        }
        clause_dd = {
            record["provision_id"]
            for record in dd_records
            if record["article"] == article and record["clause"] == clause
        }
        if clause_d and clause_dd:
            assert clause_d != clause_dd, (
                f"{doc_type} {article} {clause}: diem-d và diem-đ phải là hai ID riêng biệt"
            )


def test_full_point_runs_abcd_de() -> None:
    """nd Điều 5 Khoản 1 and luat Điều 3 Khoản 1 contain the full a-b-c-d-đ-e run."""

    by_clause: dict[str, list[str]] = {}
    for doc_type in DOC_TYPES:
        for record in _expected_core_records(doc_type):
            if record.get("point_label"):
                parent = record["provision_id"].rsplit("__diem-", 1)[0]
                by_clause.setdefault(parent, []).append(record["point_label"])

    for clause_id, labels in FULL_POINT_RUNS.items():
        assert sorted(by_clause.get(clause_id, [])) == sorted(labels), clause_id
        all_ids = {
            record["provision_id"]
            for doc_type in DOC_TYPES
            for record in _expected_core_records(doc_type)
        }
        for label in labels:
            point_id = f"{clause_id}__diem-{label.removesuffix(')')}"
            assert point_id in all_ids, f"missing {point_id}"


def test_short_points_are_retained() -> None:
    """Short Points are retained without a token-length threshold (rules §5):
    the luat Điều 8 Khoản 1 a/d/đ points are all present in the output (none
    filtered by length), the d/đ cases are marked short_point=True, and every
    short Point in the golden set is retained."""

    all_ids: set[str] = set()
    short_ids: set[str] = set()
    for doc_type in DOC_TYPES:
        for record in _expected(doc_type)["provisions"]:
            all_ids.add(record["provision_id"])
            if record.get("short_point") is True:
                short_ids.add(record["provision_id"])
                assert record["retained"] is True, (
                    f"{doc_type}: short Point {record['provision_id']} không retained"
                )

    # The ticket-named luat Điều 8 Khoản 1 cases survive extraction (retained).
    assert all_ids >= SHORT_POINT_IDS, (
        f"thiếu Point đã đặt tên: {SHORT_POINT_IDS - all_ids}"
    )
    # d/đ are flagged short_point=True by the extractor (the a) case carries the
    # label token too, so its source_text is 4 tokens — the golden set locks the
    # extractor's actual output rather than an assumed threshold).
    assert "luat-36-2024__dieu-8__khoan-1__diem-d" in short_ids
    assert "luat-36-2024__dieu-8__khoan-1__diem-đ" in short_ids
    assert short_ids, "golden set không chứa short-Point nào"
