"use client";
import { FormEvent, useState } from "react";
import AbstentionResult from "../src/components/AbstentionResult";
import CitationCard, { Citation } from "../src/components/CitationCard";
import FeedbackWidget from "../src/components/FeedbackWidget";
import ProgressEvents from "../src/components/ProgressEvents";
import SourceDrawer from "../src/components/SourceDrawer";
type Claim = { claim?: string; claim_type?: string; provision_ids?: string[] };
type ChatResponse = { status?: "VERIFIED" | "ABSTAINED"; answer?: string | null; claims?: Claim[]; citations?: Citation[]; abstention?: { reason_code?: string; reason?: string } | null; disclaimer?: string; progress_events?: Array<Record<string, unknown>>; trace_id?: string; metadata?: { query_date?: string | null; comparison_date?: string | null; vehicle?: string | null; comparison?: boolean } };
const API_PATH = "/api/v1/chat";
export default function Home() {
 const [question,setQuestion]=useState(""); const [drawerCitation,setDrawerCitation]=useState<Citation|null>(null); const [response,setResponse]=useState<ChatResponse|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!question.trim()) return; setLoading(true); setError(""); setResponse(null); try { const body={question:question.trim()}; const result=await fetch(API_PATH,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const payload=await result.json().catch(()=>null); if(!result.ok)throw new Error(payload?.error?.message||"Không thể gửi câu hỏi. Vui lòng thử lại."); setResponse(payload as ChatResponse); } catch(caught){setError(caught instanceof Error ? caught.message : "Không thể gửi câu hỏi. Vui lòng thử lại.");} finally{setLoading(false);} }
 const abstained=response?.status==="ABSTAINED"; const suggestions=["Mức phạt khi vượt đèn đỏ là bao nhiêu?","Đi xe máy không đội mũ bảo hiểm bị phạt thế nào?","Có được dùng điện thoại khi đang lái xe không?"];
 return <main className="chat-page"><div className="chat-shell"><aside className="context-panel" aria-label="Thông tin ứng dụng"><div className="brand-mark">VN</div><strong>VNLAW</strong><span>Tra cứu pháp luật</span><button type="button" className="new-conversation" onClick={()=>{setQuestion("");setResponse(null);setError("");}}>+ Cuộc trò chuyện mới</button><p className="panel-note">Câu trả lời được tổng hợp từ các văn bản pháp luật Việt Nam và luôn kèm căn cứ để bạn kiểm tra.</p></aside><section className="chat-workspace"><header className="top-bar"><div><span className="eyebrow">TRỢ LÝ PHÁP LUẬT</span><h1>Hỏi đáp pháp luật giao thông</h1></div><span className="connection-status"><i aria-hidden="true"/> Sẵn sàng</span></header><div className="conversation"><div className="empty-state"><div className="sparkle">✦</div><h2>Bạn cần tra cứu điều gì?</h2><p>Đặt câu hỏi về luật giao thông để nhận câu trả lời rõ ràng, có kiểm chứng.</p><div className="suggestions" aria-label="Gợi ý câu hỏi">{suggestions.map(item=><button key={item} type="button" onClick={()=>setQuestion(item)}>{item}<span>→</span></button>)}</div></div><form onSubmit={submit} className="query-form"><label htmlFor="question">Câu hỏi<textarea id="question" required value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ví dụ: Mức phạt khi vượt đèn đỏ là bao nhiêu?" /></label><button type="submit" disabled={loading||!question.trim()}>{loading?"Đang tra cứu...":"Gửi câu hỏi"}<span>↑</span></button></form>{error&&<p role="alert" className="error-message">{error}</p>}{response&&<section className={abstained?"response abstained":"response"}>{abstained?<AbstentionResult reason={response.abstention?.reason} reasonCode={response.abstention?.reason_code} disclaimer={response.disclaimer}/>:<><div className="response-heading"><span>Trả lời có căn cứ pháp lý</span><b>ĐÃ KIỂM CHỨNG</b></div><div className="answer-body">{response.answer}</div><ProgressEvents events={response.progress_events}/><div className="citations">{response.citations?.map((citation,index)=><CitationCard key={citation.provision_id??index} citation={citation} onOpenSource={()=>setDrawerCitation(citation)}/>)}</div>{response.trace_id&&<FeedbackWidget traceId={response.trace_id}/>}</>}</section>}</div></section></div>{drawerCitation&&<SourceDrawer citation={drawerCitation} onClose={()=>setDrawerCitation(null)}/>}</main>;
}
