"""Initial VNLaw v2 schema (VNLRAG-38).

Creates the full PostgreSQL 18 schema from an empty database, mirroring the
authoritative DDL in doc 03 §3.10.2–§3.10.4 (20 tables) plus the bootstrap
objects those sections require:

* ``CREATE EXTENSION IF NOT EXISTS btree_gist`` — required before the GiST
  exclusion constraint that compares ``varchar`` (doc 03 §3.10.4);
* ``normalize_ref_text()`` — project function (lowercase, NFKC,
  whitespace/punctuation normalization) used by the unresolved-reference
  partial unique index (doc 03 §3.10.2);
* the temporal exclusion constraint ``legal_provisions_no_overlap_accepted``
  over ``[)`` dateranges, restricted to ``review_status = 'ACCEPTED'``;
* every acceptance CHECK and the exact documented index/constraint names.

The revision is hand-written DDL (not autogenerated) so the extension,
function, exclusion constraint and partial unique index — none of which
``autogenerate`` can produce — are guaranteed to match the documentation
verbatim. ``alembic/env.py`` still targets ``app.persistence.models``
``Base.metadata`` so future revisions can be autogenerated on top of this one.

Revision ID: 0001
Revises:
Create Date: 2026-08-12
"""
# ruff: noqa: E501

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # Bootstrap (doc 03 §3.10.4): must run before any GiST exclusion
    # constraint compares varchar columns.
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # Project function for the unresolved-reference partial unique index
    # (doc 03 §3.10.2): lowercase + NFKC + whitespace/punctuation
    # normalization. Deterministic and IMMUTABLE so it can appear in an
    # index expression.
    op.execute(
        """CREATE OR REPLACE FUNCTION normalize_ref_text(ref_text text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURN btrim(
    regexp_replace(
        regexp_replace(
            lower(normalize(ref_text, NFKC)),
            '[.,;:!?()\\[\\]{}"''«»“”‘’…•]+',
            '',
            'g'
        ),
        '\\s+',
        ' ',
        'g'
    )
)"""
    )

    # ------------------------------------------------------------------
    # Tables in FK-safe creation order (doc 03 §3.10.2).
    # ------------------------------------------------------------------
    op.execute(
        """CREATE TABLE legal_sources (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id   varchar NOT NULL UNIQUE,
    source_name text NOT NULL,
    source_type varchar NOT NULL,
    base_url    text,
    priority    int NOT NULL DEFAULT 100,
    enabled     boolean NOT NULL DEFAULT true,
    notes       text,
    created_at  timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE legal_documents (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id     varchar NOT NULL UNIQUE,
    document_number varchar NOT NULL,
    document_title  text NOT NULL,
    document_type   varchar NOT NULL,
    issuer          varchar,
    issued_date     date,
    source_id       uuid REFERENCES legal_sources(id),
    source_url      text,
    downloaded_at   timestamptz,
    file_hash       varchar NOT NULL UNIQUE,
    status          varchar NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE document_versions (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id    varchar NOT NULL REFERENCES legal_documents(document_id),
    version        int NOT NULL,
    manifest_json  jsonb NOT NULL,
    content_hash   varchar NOT NULL,
    effective_from date,
    effective_to   date,
    review_status  varchar NOT NULL DEFAULT 'PENDING'
                   CONSTRAINT document_versions_review_status_check
                   CHECK (review_status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DROPPED')),
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT document_versions_pk UNIQUE (document_id, version),
    CONSTRAINT document_versions_interval_check
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    -- effective_from bắt buộc khi đã ACCEPTED (doc 03 §3.15.6)
    CONSTRAINT document_versions_effective_from_accepted_check
        CHECK (review_status <> 'ACCEPTED' OR effective_from IS NOT NULL)
)"""
    )

    op.execute(
        """CREATE TABLE legal_provisions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    provision_id        varchar NOT NULL,
    document_version_id uuid NOT NULL REFERENCES document_versions(id),
    node_kind           varchar NOT NULL DEFAULT 'ARTICLE'
                        CONSTRAINT legal_provisions_node_kind_check
                        CHECK (node_kind IN ('ARTICLE', 'CLAUSE', 'POINT', 'APPENDIX', 'TABLE', 'TRANSITIONAL', 'HEADING', 'OTHER')),
    chapter             varchar,
    section             varchar,
    article             varchar,
    clause              varchar,
    point               varchar,
    heading             varchar,
    source_text         text NOT NULL,
    retrieval_text      text NOT NULL,
    parent_context      text,
    effective_from      date,
    effective_to        date,
    status              varchar NOT NULL,
    page_number         int NOT NULL,
    bbox                jsonb,
    source_element_ids  jsonb NOT NULL DEFAULT '[]',
    content_hash        varchar NOT NULL,
    version             int NOT NULL,
    review_status       varchar NOT NULL DEFAULT 'PENDING'
                        CONSTRAINT legal_provisions_review_status_check
                        CHECK (review_status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DROPPED')),
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT legal_provisions_pk UNIQUE (provision_id, version),
    CONSTRAINT legal_provisions_interval_check
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    -- Article bắt buộc trừ các node ngoài cây Điều thường
    -- (Appendix/Table/Heading/Transitional/Other)
    CONSTRAINT legal_provisions_article_required
        CHECK (article IS NOT NULL OR node_kind IN ('APPENDIX', 'TABLE', 'HEADING', 'TRANSITIONAL', 'OTHER')),
    -- effective_from bắt buộc khi đã ACCEPTED (ràng buộc thời gian, doc 03 §3.15.6)
    CONSTRAINT legal_provisions_effective_from_accepted_check
        CHECK (review_status <> 'ACCEPTED' OR effective_from IS NOT NULL),
    -- Không có hai version ACCEPTED chồng lấn trong cùng provision
    -- (doc 03 §3.10.4); cần btree_gist (bootstrap ở trên) vì provision_id
    -- là varchar so sánh bằng trong GiST.
    CONSTRAINT legal_provisions_no_overlap_accepted
        EXCLUDE USING gist (
            provision_id WITH =,
            daterange(effective_from, effective_to, '[)') WITH &&
        )
        WHERE (review_status = 'ACCEPTED')
)"""
    )

    op.execute(
        """CREATE TABLE provision_versions (
    id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    provision_id           varchar NOT NULL,
    version                int NOT NULL,
    document_version_id    uuid NOT NULL REFERENCES document_versions(id),
    superseded_by_version  int,
    created_at             timestamptz NOT NULL DEFAULT now(),
    created_by             varchar,
    CONSTRAINT provision_versions_pk UNIQUE (provision_id, version),
    CONSTRAINT provision_versions_fk
        FOREIGN KEY (provision_id, version)
        REFERENCES legal_provisions(provision_id, version)
)"""
    )

    op.execute(
        """CREATE TABLE provision_references (
    id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    -- FK vật lý tới row version cụ thể trong legal_provisions
    source_legal_provision_id   uuid NOT NULL REFERENCES legal_provisions(id),
    target_legal_provision_id   uuid REFERENCES legal_provisions(id),
    -- Cột logical để query/debug (không phải FK)
    source_provision_id         varchar NOT NULL,
    source_provision_version_id varchar,
    target_provision_id         varchar,
    target_provision_version_id varchar,
    relation_type               varchar NOT NULL
                                CONSTRAINT provision_references_relation_type_check
                                CHECK (relation_type IN ('PARENT_OF', 'REFERS_TO', 'SIBLING_OF', 'PENALTY_COMPANION')),
    confidence                  real,
    extraction_method           varchar NOT NULL,
    source_text                 text NOT NULL,
    resolution_status           varchar NOT NULL DEFAULT 'UNRESOLVED'
                                CONSTRAINT provision_references_resolution_status_check
                                CHECK (resolution_status IN ('RESOLVED', 'UNRESOLVED', 'PENDING_REVIEW')),
    review_status               varchar NOT NULL DEFAULT 'PENDING'
                                CONSTRAINT provision_references_review_status_check
                                CHECK (review_status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DROPPED')),
    created_at                  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT provision_references_target_resolution_check
        CHECK (
            (resolution_status = 'UNRESOLVED' AND target_legal_provision_id IS NULL)
            OR (
                resolution_status IN ('RESOLVED', 'PENDING_REVIEW')
                AND target_legal_provision_id IS NOT NULL
            )
        ),
    CONSTRAINT provision_references_resolved_pk
        UNIQUE (source_legal_provision_id, target_legal_provision_id, relation_type)
)"""
    )

    op.execute(
        """CREATE TABLE document_relations (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    source_document_id  varchar NOT NULL,
    target_document_id  varchar NOT NULL,
    relation_type       varchar NOT NULL
                        CONSTRAINT document_relations_relation_type_check
                        CHECK (relation_type IN ('AMENDS', 'REPEALS', 'SUPERSEDES', 'CORRECTS', 'GUIDES', 'RELATED_TO')),
    effective_from      date,
    source_note         text,
    confidence          real,
    source              varchar NOT NULL,
    resolution_status   varchar NOT NULL DEFAULT 'RESOLVED'
                        CONSTRAINT document_relations_resolution_status_check
                        CHECK (resolution_status IN ('RESOLVED', 'UNRESOLVED', 'PENDING_REVIEW')),
    review_status       varchar NOT NULL DEFAULT 'PENDING'
                        CONSTRAINT document_relations_review_status_check
                        CHECK (review_status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DROPPED')),
    created_at          timestamptz NOT NULL DEFAULT now(),
    reviewed_by         varchar,
    reviewed_at         timestamptz,
    CONSTRAINT document_relations_pk
        UNIQUE (source_document_id, target_document_id, relation_type)
)"""
    )

    op.execute(
        """CREATE TABLE legal_effect_events (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id        varchar NOT NULL,
    event_type         varchar NOT NULL
                       CONSTRAINT legal_effect_events_event_type_check
                       CHECK (event_type IN ('EFFECTIVE', 'AMENDED', 'SUPERSEDED', 'REPEALED', 'CORRECTED', 'EXPIRED', 'PARTIAL_AMENDED')),
    event_date         date NOT NULL,
    source_document_id varchar,
    description        text,
    source_reference   text,
    affected_provision_versions jsonb NOT NULL DEFAULT '[]',
    confidence         real,
    review_status      varchar NOT NULL DEFAULT 'PENDING'
                       CONSTRAINT legal_effect_events_review_status_check
                       CHECK (review_status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DROPPED')),
    created_at         timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE parsed_documents (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id        varchar NOT NULL REFERENCES legal_documents(document_id),
    parser             varchar NOT NULL,
    parser_version     varchar NOT NULL,
    ir_schema_version  varchar NOT NULL,
    source_object_key  varchar NOT NULL,
    parse_status       varchar NOT NULL,
    quality_report     jsonb,
    started_at         timestamptz,
    completed_at       timestamptz
)"""
    )

    op.execute(
        """CREATE TABLE document_elements (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    parsed_document_id uuid NOT NULL REFERENCES parsed_documents(id),
    element_id         varchar NOT NULL,
    element_type       varchar NOT NULL,
    text               text NOT NULL,
    page_number        int NOT NULL,
    bbox               jsonb,
    reading_order      int NOT NULL,
    parent_element_id  varchar,
    table_html         text,
    source_parser      varchar NOT NULL,
    parser_version     varchar NOT NULL,
    parser_confidence  real,
    raw_reference      jsonb,
    CONSTRAINT document_elements_pk UNIQUE (parsed_document_id, element_id)
)"""
    )

    op.execute(
        """CREATE TABLE provision_provenances (
    id                         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    provision_version_row_id   uuid NOT NULL REFERENCES legal_provisions(id),
    source_document_version_id uuid NOT NULL REFERENCES document_versions(id),
    source_element_id          varchar NOT NULL,
    page_number                int NOT NULL,
    bbox                       jsonb,
    role                       varchar NOT NULL
                               CONSTRAINT provision_provenances_role_check
                               CHECK (role IN ('BASE_TEXT', 'AMENDMENT_TEXT', 'CORRECTION_TEXT', 'EFFECT_SOURCE')),
    created_at                 timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE ingestion_runs (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id         varchar NOT NULL UNIQUE,
    document_id    varchar NOT NULL REFERENCES legal_documents(document_id),
    manifest_json  jsonb NOT NULL,
    file_hash      varchar NOT NULL,
    status         varchar NOT NULL,
    current_stage  varchar,
    parser_routing jsonb,
    started_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    completed_at   timestamptz,
    error          jsonb,
    retry_count    int NOT NULL DEFAULT 0
)"""
    )

    op.execute(
        """CREATE TABLE ingestion_artifacts (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    ingestion_run_id uuid NOT NULL REFERENCES ingestion_runs(id),
    artifact_type    varchar NOT NULL,
    bucket           varchar NOT NULL,
    object_key       varchar NOT NULL,
    file_hash        varchar,
    size             bigint NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE review_items (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    ingestion_run_id uuid NOT NULL REFERENCES ingestion_runs(id),
    document_id      varchar NOT NULL,
    target_type      varchar NOT NULL,
    target_id        varchar NOT NULL,
    reason_code      varchar NOT NULL,
    description      text,
    evidence         jsonb,
    status           varchar NOT NULL DEFAULT 'PENDING'
                     CONSTRAINT review_items_status_check
                     CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DROPPED')),
    reviewer         varchar,
    reviewed_at      timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE query_traces (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    trace_id             varchar NOT NULL UNIQUE,
    question             text NOT NULL,
    intent               varchar NOT NULL,
    query_date           date,
    comparison_from      date,
    comparison_to        date,
    vehicle_type         varchar,
    response_status      varchar NOT NULL,
    answer_type          varchar,
    latency_ms           int,
    estimated_cost       numeric(12, 4),
    token_usage          jsonb,
    citations            jsonb,
    verification_summary jsonb,
    langfuse_trace_id    varchar,
    config_snapshot      jsonb,
    created_at           timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE query_feedback (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    query_trace_id uuid NOT NULL REFERENCES query_traces(id),
    useful         boolean NOT NULL,
    category       varchar
                   CONSTRAINT query_feedback_category_check
                   CHECK (category IN ('wrong_citation', 'missing_information', 'wrong_effective_date',
                                       'wrong_penalty', 'incomplete_answer', 'other')),
    comment        text,
    created_at     timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE evaluation_datasets (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    dataset_id     varchar NOT NULL UNIQUE,
    name           varchar NOT NULL,
    split          varchar NOT NULL
                   CONSTRAINT evaluation_datasets_split_check
                   CHECK (split IN ('DEVELOPMENT', 'VALIDATION', 'FINAL_TEST')),
    version        varchar NOT NULL,
    hash           varchar NOT NULL,
    questions_path text NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now()
)"""
    )

    op.execute(
        """CREATE TABLE evaluation_runs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id            varchar NOT NULL UNIQUE,
    git_commit        varchar NOT NULL,
    corpus_version    varchar NOT NULL,
    corpus_hash       varchar NOT NULL,
    gold_set_version  varchar NOT NULL,
    gold_set_hash     varchar NOT NULL,
    suite             varchar NOT NULL,
    variant           varchar NOT NULL,
    run_manifest_hash varchar NOT NULL,
    config_snapshot   jsonb NOT NULL,
    model_ids         jsonb NOT NULL,
    prompt_versions   jsonb NOT NULL,
    parser_versions   jsonb NOT NULL,
    status            varchar NOT NULL DEFAULT 'RUNNING',
    metrics           jsonb,
    raw_results_path  text NOT NULL,
    started_at        timestamptz NOT NULL DEFAULT now(),
    completed_at      timestamptz
)"""
    )

    op.execute(
        """CREATE TABLE evaluation_results (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    evaluation_run_id uuid NOT NULL REFERENCES evaluation_runs(id),
    question_id       varchar NOT NULL,
    input             jsonb NOT NULL,
    retrieval         jsonb NOT NULL,
    output            jsonb NOT NULL,
    metrics           jsonb NOT NULL,
    raw_results_path  text
)"""
    )

    op.execute(
        """CREATE TABLE corpus_qa_reports (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id          varchar NOT NULL UNIQUE,
    corpus_version     varchar NOT NULL,
    corpus_hash        varchar NOT NULL,
    metrics            jsonb NOT NULL,
    documents_analyzed jsonb,
    notes              text,
    generated_at       timestamptz NOT NULL DEFAULT now()
)"""
    )

    # ------------------------------------------------------------------
    # Indexes (doc 03 §3.10.3 + §3.10.2 inline index + partial unique).
    # The unresolved-reference partial unique index depends on
    # normalize_ref_text(), created in the bootstrap above.
    # ------------------------------------------------------------------
    op.execute("CREATE INDEX idx_legal_documents_number ON legal_documents (document_number)")
    op.execute(
        "CREATE INDEX idx_document_versions_document ON document_versions (document_id, version)"
    )
    op.execute(
        "CREATE INDEX idx_legal_provisions_hierarchy ON legal_provisions (document_version_id, article, clause, point)"
    )
    op.execute(
        "CREATE INDEX idx_legal_provisions_interval ON legal_provisions (effective_from, effective_to)"
    )
    op.execute(
        "CREATE INDEX idx_legal_provisions_review_status ON legal_provisions (review_status) WHERE review_status = 'ACCEPTED'"
    )
    op.execute(
        "CREATE INDEX idx_provision_versions_provision ON provision_versions (provision_id, version)"
    )
    op.execute(
        "CREATE INDEX idx_provision_references_source ON provision_references (source_provision_id)"
    )
    op.execute(
        "CREATE INDEX idx_provision_references_target ON provision_references (target_provision_id)"
    )
    op.execute("CREATE INDEX idx_provision_references_type ON provision_references (relation_type)")
    op.execute(
        "CREATE INDEX idx_document_relations_source ON document_relations (source_document_id)"
    )
    op.execute(
        "CREATE INDEX idx_document_relations_target ON document_relations (target_document_id)"
    )
    op.execute(
        "CREATE INDEX idx_legal_effect_events_document ON legal_effect_events (document_id, event_date)"
    )
    op.execute(
        "CREATE INDEX idx_document_elements_parsed ON document_elements (parsed_document_id, page_number, reading_order)"
    )
    op.execute("CREATE INDEX idx_ingestion_runs_status ON ingestion_runs (status)")
    op.execute("CREATE INDEX idx_review_items_status ON review_items (status)")
    op.execute("CREATE INDEX idx_query_traces_created_at ON query_traces (created_at)")
    op.execute("CREATE INDEX idx_query_feedback_trace ON query_feedback (query_trace_id)")
    op.execute("CREATE INDEX idx_evaluation_results_run ON evaluation_results (evaluation_run_id)")
    op.execute(
        "CREATE INDEX idx_provision_provenances_version ON provision_provenances (provision_version_row_id)"
    )
    op.execute(
        """CREATE UNIQUE INDEX provision_references_unresolved_pk
    ON provision_references (
        source_legal_provision_id,
        relation_type,
        md5(normalize_ref_text(source_text))
    )
    WHERE (resolution_status = 'UNRESOLVED' AND target_legal_provision_id IS NULL)"""
    )


def downgrade() -> None:
    """Drop the schema in reverse FK order, then the bootstrap objects."""
    op.execute(
        """DROP TABLE IF EXISTS
    corpus_qa_reports,
    evaluation_results,
    evaluation_runs,
    evaluation_datasets,
    query_feedback,
    query_traces,
    review_items,
    ingestion_artifacts,
    ingestion_runs,
    provision_provenances,
    document_elements,
    parsed_documents,
    legal_effect_events,
    document_relations,
    provision_references,
    provision_versions,
    legal_provisions,
    document_versions,
    legal_documents,
    legal_sources
"""
    )
    op.execute("DROP FUNCTION IF EXISTS normalize_ref_text(text)")
